### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by saramortara** [saramortara/manuscript_niche_neutral#1]
- [x] standardize nomenclature according to Vellend (niche-neutral now selection-drift)
- [x] update text box
- [x] update tables
- [x] change figure's color palette
- [x] describe results for core species (response to trait)
- [x] separate tutorial from supporting info
- [x] add graphics to supporting info
- [ ] update .bib
- [ ] cover letter
- [ ] response letter
